#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fix GBK garbled characters in C# files
Converts garbled characters back to proper Chinese
"""

import os
import re

# Mapping of garbled sequences to correct Chinese characters
# This is based on common GBK->UTF-8 conversion errors
REPLACEMENTS = {
    # Common patterns
    "���ݿ�": "数据库",
    "��ʼ��": "初始化",
    "��ȡ": "获取",
    "�ļ�": "文件",
    "·��": "路径",
    "��Ϣ": "信息",
    "����": "设置",
    "״̬": "状态",
    "��־": "日志",
    "��": "是否",
    "����": "启用",
    "ֹͣ": "停止",
    "��ʼ": "开始",
    "ִ��": "执行",
    "����": "处理",
    "ʧ��": "失败",
    "�ɹ�": "成功",
    "����": "添加",
    "ɾ��": "删除",
    "�޸�": "修改",
    "��ѯ": "查询",
    "����": "保存",
    "���": "加载",
    "�߳�": "线程",
    "����": "队列",
    "����": "批量",
    "дlong": "写入",
    "��ȡ": "读取",
    "�¼�": "事件",
    "�ص�": "回调",
    "������": "注册表",
    "ע��": "注册",
    "ȡ��ע��": "取消注册",
    "�����": "参数",
    "����": "配置",
    "�����": "工作站",
    "�����": "操作员",
    "�û�": "用户",
    "����": "密码",
    "��¼": "登录",
    "�˳�": "退出",
    "Ȩ��": "权限",
    "��ɫ": "角色",
    "����": "管理",
    "ͳ��": "统计",
    "������": "报警表",
    "��": "告警",
    "��": "警告",
    "����": "错误",
    "�쳣": "异常",
    "��": "调试",
    "��": "跟踪",
    "����": "缺陷",
    "��": "类型",
    "����": "代码",
    "��": "内容",
    "��": "位置",
    "ʱ��": "时间",
    "���": "日期",
    "����": "时刻",
    "����": "记录",
    "��": "批次",
    "����": "序列号",
    "��": "产品",
    "ģ��": "型号",
    "��": "材料",
    "����": "托盘",
    "��": "结果",
    "��OK": "良品",
    "NG": "不良",
    "��Ʒ": "良品",
    "��": "合格",
    "��": "不合格",
    "���": "测试",
    "��": "检测",
    "��ӱ": "视觉",
    "ͼ��": "图像",
    "·��": "路径",
    "��": "尺寸",
    "��": "角度",
    "��": "间隙",
    "��": "厚度",
    "ֱ": "直径",
    "�ڱ": "周期",
    "ʱ": "时间",
    "�¶�": "温度",
    "ʪ��": "湿度",
    "ѹ��": "压力",
    "��": "追溯",
    "��": "上游",
    "�": "下游",
    "��": "返工",
    "��": "次数",
    "��": "备注",
    "����": "扩展",
    "�": "数据",
    "��": "字段",
    "ֵ": "值",
    "��": "描述",
    "˵��": "说明",
    "��": "更新",
    "����": "刷新",
    "��": "清除",
    "ȷ��": "确认",
    "ȡ��": "取消",
    "�": "提示",
    "��": "警告",
    "��": "帮助",
    "��": "关闭",
    "�˳�": "退出",
    "��": "运动",
    "��": "控制",
    "��": "轴",
    "λ": "位置",
    "��": "目标",
    "��": "当前",
    "��": "移动",
    "ֹ": "停止",
    "��": "回零",
    "����": "原点",
    "��": "限位",
    "��": "伺服",
    "��": "使能",
    "��": "报警",
    "��": "到位",
    "��": "运行",
    "��": "复位",
    "��": "急停",
    "��": "定位",
    "��": "速度",
    "���": "加速度",
    "ģʽ": "模式",
    "��": "绝对",
    "��": "相对",
    "JOG": "JOG",
    "��": "连续",
    "��": "步进",
    "�": "距离",
    "��": "方向",
    "��": "保存",
    "�": "点位",
    "��": "编辑",
    "ɾ": "删除",
    "��": "移动到",
    "��": "重命名",
    "��": "导入",
    "��": "导出",
    "��": "扫码",
    "��": "管理",
    "��": "条码",
    "ɨ��": "扫描",
    "ɨ��": "扫描枪",
    "��": "串口",
    "��": "键盘",
    "��": "手动",
    "��": "输入",
    "��": "验证",
    "��": "格式",
    "��": "正确",
    "��": "错误",
    "��": "重复",
    "��": "存在",
    "��": "不存在",
    "��": "列表",
    "��": "历史",
    "��": "清空",
    "��": "颜色",
    "���": "显示",
    "���": "隐藏",
    "��": "刷新",
    "���": "界面",
    "��": "窗口",
    "��": "对话框",
    "��": "控件",
    "��": "按钮",
    "��": "文本框",
    "��": "标签",
    "��": "列表框",
    "��": "下拉框",
    "��": "选择",
    "��": "全部",
    "��": "部分",
    "��": "单个",
    "��": "多个",
    "��": "第一个",
    "��": "最后一个",
    "��": "下一个",
    "��": "上一个",
    "��": "索引",
    "��": "计数",
    "��": "数量",
    "��": "总数",
    "��": "平均",
    "��": "最大",
    "��": "最小",
    "��": "求和",
    "��": "百分比",
    "��": "比率",
    "��": "得率",
    "��": "良率",
    "��": "效率",
    "��": "性能",
    "��": "优化",
    "��": "延迟",
    "��": "超时",
    "��": "重试",
    "��": "次数",
    "��": "间隔",
    "��": "周期",
    "��": "频率",
    "��": "采样",
    "��": "监控",
    "��": "分析",
    "��": "图表",
    "��": "曲线",
    "��": "趋势",
    "��": "对比",
    "��": "筛选",
    "��": "排序",
    "��": "分组",
    "��": "汇总",
    "��": "明细",
    "��": "详细",
    "��": "简单",
    "��": "复杂",
    "��": "高级",
    "��": "基本",
    "��": "默认",
    "��": "自定义",
    "��": "系统",
    "��": "应用",
    "��": "程序",
    "��": "项目",
    "��": "版本",
    "��": "作者",
    "��": "日期",
    "��": "说明",
    "��": "备注",
    "��": "注释",
    "��": "文档",
    "��": "帮助",
    "��": "示例",
    "��": "测试",
    "��": "调试",
    "��": "发布",
    "��": "部署",
    "��": "安装",
    "��": "卸载",
    "��": "升级",
    "��": "降级",
    "��": "迁移",
    "��": "备份",
    "��": "恢复",
    "��": "导入",
    "��": "导出",
    "��": "同步",
    "��": "异步",
    "��": "并发",
    "��": "串行",
    "��": "并行",
    "��": "顺序",
    "��": "随机",
    "��": "排列",
    "��": "组合",
    "��": "算法",
    "��": "逻辑",
    "��": "流程",
    "��": "步骤",
    "��": "阶段",
    "��": "环节",
    "��": "模块",
    "��": "组件",
    "��": "服务",
    "��": "接口",
    "��": "实现",
    "��": "抽象",
    "��": "继承",
    "��": "封装",
    "��": "多态",
    "��": "单例",
    "��": "工厂",
    "��": "建造者",
    "��": "观察者",
    "��": "策略",
    "��": "模板",
    "��": "装饰器",
    "��": "代理",
    "��": "适配器",
    "��": "门面",
    "��": "桥接",
    "��": "组合",
    "��": "享元",
    "��": "责任链",
    "��": "命令",
    "��": "解释器",
    "��": "迭代器",
    "��": "中介者",
    "��": "备忘录",
    "��": "原型",
    "��": "状态",
    "��": "访问者",
}

def fix_file(file_path):
    """Fix garbled characters in a single file"""
    try:
        print(f"Processing: {file_path}")
        
        # Read file content
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        
        original_content = content
        
        # Apply replacements
        for garbled, correct in REPLACEMENTS.items():
            if garbled in content:
                count = content.count(garbled)
                content = content.replace(garbled, correct)
                print(f"  - Replaced '{garbled}' -> '{correct}' ({count} times)")
        
        # Check if any changes were made
        if content != original_content:
            # Write back to file
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"  ✓ File updated successfully")
            return True
        else:
            print(f"  - No changes needed")
            return False
            
    except Exception as e:
        print(f"  ✗ Error processing file: {e}")
        return False

def main():
    """Main function to fix all specified files"""
    files = [
        "/Users/james/Desktop/workspace/Auto/COTUI/通用功能类/DatabaseLoggerExtension.cs",
        "/Users/james/Desktop/workspace/Auto/COTUI/扫码管理/BarcodeScanPage.cs",
        "/Users/james/Desktop/workspace/Auto/COTUI/扫码管理/ProductSNManager.cs",
        "/Users/james/Desktop/workspace/Auto/COTUI/数据库/DatabaseHelper.cs",
        "/Users/james/Desktop/workspace/Auto/COTUI/数据库/Services/ProductionDataService.cs",
        "/Users/james/Desktop/workspace/Auto/COTUI/数据库/Services/AlarmService.cs",
        "/Users/james/Desktop/workspace/Auto/COTUI/数据库/Services/LogService.cs",
        "/Users/james/Desktop/workspace/Auto/COTUI/数据库/Services/UserService.cs",
        "/Users/james/Desktop/workspace/Auto/COTUI/运动控制页面/MotionControlPage.cs",
    ]
    
    print("=" * 80)
    print("Starting GBK garbled character fix...")
    print("=" * 80)
    
    total_files = len(files)
    fixed_files = 0
    
    for file_path in files:
        if os.path.exists(file_path):
            if fix_file(file_path):
                fixed_files += 1
        else:
            print(f"File not found: {file_path}")
        print()
    
    print("=" * 80)
    print(f"Summary: Fixed {fixed_files} out of {total_files} files")
    print("=" * 80)

if __name__ == "__main__":
    main()
